### ISSUE TITLE
Feature request: example use of multiple currencies

### ISSUE THREAD

**Issue by elkelk** [Shopify/hydrogen-examples#5]
Due to the fact that Shopify GraphQL queries require inContext decorators for currency selection and that there is a GraphQL limit of number of requests, all international requests that are not USD will need to re-query all products and cart data. It would be great to provide an example that shows how to properly deal with multiple currencies and also how to support client selection of currency from the front end.

**Comment by scottdixon** [comment]
Hey @elkelk! There's an example in the latest starter template.

```
yarn create hydrogen-app
```
