### ISSUE TITLE
How can we remove the abbreviation for prices

### ISSUE THREAD

**Issue by joshbedo** [Shopify/hydrogen-examples#6]
Tried finding a setting and going through the documentation but cant figure out how to remove the CA abbreviation for prices in the CartLine component.

<img width="1782" alt="The Cha-Ching Button - supply-hydrogen-reference 2021-11-16 01-29-27" src="https://user-images.githubusercontent.com/607239/141933396-c38a34e5-587b-40d2-8ee0-49d2af6fcc54.png">

**Comment by scottdixon** [comment]
Hey @joshbedo!

Each of these components render a [`Money`](https://shopify.dev/api/hydrogen/components/primitive/money) component which outputs a currency code.

[I've created a discussion](https://github.com/Shopify/hydrogen/discussions/307). In the meantime, you could replace `<CartLine.Price />` and `<CartEstimatedCost />` with your own components. For example, a line item price might look something like this:

```
<CartLines>
  {({merchandise, quantity}) => {
    ...
    <span>${ merchandise.priceV2.amount * quantity }</span>
    ...
  )}}
</CartLines>
```

**Comment by scottdixon** [comment]
Hey @joshbedo

You could pass a child prop with your own formatting. You've got access to [these values](https://shopify.dev/api/hydrogen/hooks/primitive/usemoney#return-value). Something like this:

```
 <CartLine.Price>{({amount}) => amount}</CartLine.Price>
```
